config/routes.rb
Rails.application.routes.draw do
  
  root 'companies#top'

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords'
  }

  resources :users, only: [:show, :edit, :update, :destroy]

  post 'rooms/:room_id/messages' => 'messages#create', as: "messages"
  get 'search' => 'recruits#search'
  get 'entries' => 'entries#index'
  get 'bookmarks' => 'bookmarks#index'
  get 'follows' => 'follows#index'

  resources :companies, only: [:show, :new, :create] do
    get 'users/:id/become_employee' => 'users#become_employee', as: 'become_employee'
    resources :rooms, only: [:show]
    resources :follows, only: [:create, :destroy]
  end

  get 'companies/:id/feeds' => 'feeds#company_feed', as: 'company_feed'
  get 'companies/:id/recruits' => 'recruits#company_index', as: 'company_index'
  get 'companies/:id/about' => 'companies#about', as: 'about'
  get 'companies/:id/members' => 'companies#member', as: 'member'

  resources :recruits, only: [:index, :show] do
    resources :entries, only: [:create]
    resources :supports, only: [:create]
    post 'bookmarks' => 'bookmarks#create'
    delete 'bookmarks' => 'bookmarks#destroy'
  end  

  resources :feeds, only: [:index, :show] do
    post 'favorites' => 'favorites#create'
    delete 'favorites' => 'favorites#destroy'
  end

  namespace :admin do
    post 'companies/:company_id/users/:id/add_employee' => 'companies#add_employee', as: 'add_employee'
    post 'companies/:company_id/users/:id/add_authority' => 'companies#add_authority', as: 'add_authority'
    get 'companies/:id/home' => 'companies#home'
    get 'companies/:id/users' => 'companies#employee_index', as: 'employee_index'
    get 'companies/:id/invite' => 'companies#invite', as: 'invite'
    get 'companies/:id/invite_new' => 'companies#invite_new', as: 'invite_new'
     
    resources :companies, only: [:edit, :update, :destroy] do
      resources :feeds, except: [:show]
      resources :recruits, except: [:show]
      post 'feeds/:id/update_status' => 'feeds#update_status', as: 'feed_update_status'
      post 'recruits/:id/update_status' => 'recruits#update_status', as: 'recruit_update_status'
      get 'candidates/:id' => 'entries#candidate_show', as: "candidate_show"
      get 'candidates' => 'entries#candidate_list'
    end 

    post 'companies/:company_id/users/:id/remove_employee' => 'companies#remove_employee', as: 'remove_employee'
    post 'companies/:company_id/users/:id/remove_authority' => 'companies#remove_authority', as: 'remove_authority'

    get 'scouts/search' => 'scouts#search'
    post 'users/:user_id/scouts' => 'scouts#create', as: 'scouts'
  end  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
    has_many :users
    has_many :addresses, dependent: :destroy
    has_many :feeds, dependent: :destroy
    has_many :follows, dependent: :destroy
    has_many :scouts, dependent: :destroy
    has_many :recruits, dependent: :destroy
    has_many :rooms, dependent: :destroy

    acts_as_paranoid

    accepts_nested_attributes_for :addresses, allow_destroy: true

    attachment :logo

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    VALID_PHONE_NUMBER_REGEX = /\A\d{10,11}\z/

   
    validates :company_name, :person_name, presence: true, on: :create
    validates :email, format: { with: VALID_EMAIL_REGEX }, presence: true, on: :create
    validates :phone_number, format: { with: VALID_PHONE_NUMBER_REGEX }, presence: true, on: :create
    
    def self.company_search(search)
        return Company.all unless search
        Company.where(['company_name LIKE ?', "%#{search}%"])
    end
end

app/controllers/admin/companies_controller.rb
class Admin::CompaniesController < ApplicationController
	before_action :admin_user?, except: [:add_employee]

	def home
	end

	def edit
	    @company.addresses.build
	end

	def update
		if @company.update!(company_params)
			flash[:success] = "会社情報を更新しました。"
			redirect_to admin_path(@admin)
		else
			flash.now[:alert] = "更新に失敗しました。"
			render :edit
		end
	end

	def destroy
		@company = Company.find(params[:id])
		@company.destroy
		flash[:alert] = "会社アカウントを削除しました。"
		redirect_to recruits_path
	end

	def employee_index
		@members = @company.users
	end

	def invite_new
	end

	def invite
		if params[:email]
			user = User.find_by(email: params[:email])
			if user.company_id == nil || user.company_id != @company.id
				CompanyMailer.send_mail(user, @company).deliver
				flash[:info] = "招待メールを送りました。"
				redirect_to admin_employee_index_path
			else
				flash.now[:alert] = "すでに社員登録されています。"
				render :invite_new
			end
		end
	end

	def add_employee
		company = Company.find(params[:company_id])
		user = User.find(params[:id])
		user.company_id = company.id
		user.authority_status = "general"
		user.save
		flash[:success] = "社員登録に成功しました。"
		redirect_to recruits_path
	end

	def remove_employee
		member = User.find(params[:id])
		member.company_id = nil
		member.save
		flash[:alert] = "社員登録を解除しました。"
		redirect_to admin_employee_index_path
	end

	def add_authority
		member = User.find(params[:id])
		member.authority_status = "admin"
		member.save
		flash[:success] = "管理者権限を付与しました。"
		redirect_to admin_employee_index_path(member.company)
	end

	def remove_authority
		member = User.find(params[:id])
		member.authority_status = "general"
		member.save
		flash[:alert] = "管理者権限を削除しました。"
		redirect_to admin_employee_index_path(@admin.company)
	end

	private

	def admin_user?
		if current_user.authority_status == "admin"
			@admin = current_user
			@company = @admin.company
		elsif user_signed_in?
			redirect_to recruits_path
		else
			redirect_to root_path
		end
	end

	def company_params
		params.require(:company).permit(:logo, :establish_year, :establish_month, :link, :mission_title, :mission_body, :value, :what, :why, :how, addresses_attributes: [:id, :head_status, :postal_code, :prefecture, :address, :latitude, :longitude, :_destroy])
	end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  def top
  end

  def about
    @company = Company.find(params[:id])
    @headquarters = @company.addresses.find_by(head_status: "head")
  end

  def member
    @company = Company.find(params[:id])
    @headquarters = @company.addresses.find_by(head_status: "head")
    @members = @company.users
  end

  def show
    @company = Company.find(params[:id])
    @headquarters = @company.addresses.find_by(head_status: "head")
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    if User.find_by(email: @company.email)
      admin = User.find_by(email: @company.email)
      if admin.company_id.present?
        flash.now[:alert] = "会社の登録に失敗しました。"
        render :new
      else
        admin.name = @company.person_name
        admin.phone_number = @company.phone_number
        admin.authority_status = "admin"
        if @company.save
          admin.company_id = @company.id
          if admin.save
            sign_in(admin)
            flash[:success] = "会社を登録しました。"
            redirect_to edit_admin_company_path(@company)
          else
            @company.really_destroy!
            flash.now[:alert] = "会社の登録に失敗しました。"
            render :new
          end
        else
          flash.now[:alert] = "会社の登録に失敗しました。"
          render :new
        end
      end
    else
      admin = User.new
      admin.name = @company.person_name
      admin.email = @company.email
      admin.phone_number = @company.phone_number
      admin.authority_status = "admin"
      generated_password = Devise.friendly_token.first(12)
      admin.password = generated_password
      if @company.save
        admin.company_id = @company.id
        if admin.save(validate: false)
          sign_in(admin)
          PasswordMailer.send_password(admin, generated_password).deliver
          flash[:success] = "会社を登録しました。"
          redirect_to edit_admin_company_path(@company)
        else
          @company.really_destroy!
          flash.now[:alert] = "会社の登録に失敗しました。"
          render :new
        end
      else
        flash.now[:alert] = "会社の登録に失敗しました。"
        render :new
      end
    end

    
  end

  private

  def company_params
    params.require(:company).permit(:company_name, :person_name, :email, :phone_number)
  end

end

app/helpers/admin/companies_helper.rb
module Admin::CompaniesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
    class ErrorFormBuilder < ActionView::Helpers::FormBuilder
        def pick_errors(attribute)
            return nil if @object.nil? || (messages = @object.errors.messages[attribute]).nil?

            lis = messages.collect do |message|
                %{<li>#{@object.errors.full_message(attribute, message)}</li>}
            end.join

            %{<ul class="errors">#{lis}</ul}.html_safe
        end

        def text_field(attribute, options={})
            return super if options[:no_errors]
            super + pick_errors(attribute)
        end
    end
end

app/views/admin/companies/_address_fields.html.erb
<div class="nested-fields">
	<h3><strong>住所</strong></h3>
	<%= link_to_remove_association "この住所を削除", f, class: "btn btn-danger" %>
	<section class="form-group clearfix">
		<%= f.label :郵便番号, class: "col-sm-4" %>
		<div class="col-sm-8">
			<%= f.text_field :postal_code, class: "form-control" %><br>		
		</div>
	</section>
	<section class="form-group clearfix">
		<%= f.label :都道府県, class: "col-sm-4" %>
		<div class="col-sm-8">
			<%= f.text_field :prefecture, class: "form-control" %><br>
		</div>
	</section>
	<section class="form-group clearfix">
		<%= f.label :住所, class: "col-sm-4" %>
		<div class="col-sm-8">
			<%= f.text_field :address, class: "form-control" %><br>
		</div>
	</section>
	<section class="form-group clearfix">
		<%= f.label :本社ステータス, class: "col-sm-4" %>
		<div class="col-sm-8">
			<%= f.radio_button :head_status, :head, class: "form-check-input" %>
			<%= f.label :head_status, "本社" %>
			<%= f.radio_button :head_status, :branch, class: "form-check-input" %>
			<%= f.label :head_status, "支社" %>	
		</div>
		
	</section>
	
</div>

app/views/admin/companies/_sidebar.html.erb
<div class="col-sm-3">
	<ul>
		<li class="sidebar-component"><%= company.company_name %></li>
		<li class="sidebar-component">
			<%= link_to admin_path(company) do %>
				<i class="fas fa-home"></i><span>ホーム</span>
			<% end %>
		</li>
		<li class="sidebar-component">
			<%= link_to admin_company_recruits_path(company) do %>
				<i class="fas fa-bullhorn"></i><span>募集</span>
			<% end %>
		</li>
		<li class="sidebar-component">
			<%= link_to admin_company_feeds_path(company) do %>
				<i class="fas fa-newspaper"></i><span>フィード</span>
			<% end %>
		</li>
		<li class="sidebar-component">
			<%= link_to admin_company_candidates_path(company) do %>
				<i class="fas fa-user-friends"></i><span>候補者</span>
			<% end %>
		</li>
		<li class="sidebar-component">
			<%= link_to admin_scouts_search_path do %>
				<i class="fas fa-hands-helping"></i><span>スカウト</span>
			<% end %>
		</li>
	</ul>
</div>

app/views/admin/companies/edit.html.erb
<%= render 'sidebar', company: @company %>
<div class="col-sm-7"> 
	<h2 class="text-center">会社情報編集</h2>
	<%= form_with model: @company, local: true, url: admin_company_path do |f| %>
		<section class="form-group clearfix">
			<%= f.label :ロゴ, class: "col-sm-4" %>
			<div class="col-sm-8">
				<%= f.attachment_field :logo, class: "btn btn-file" %>
			</div>
		</section>
		<section class="form-group clearfix">
			<%= f.label :設立年, class: "col-sm-4" %>
			<div class="col-sm-8">
				<%= f.number_field :establish_year, class: "form-control" %>
			</div>
		</section>
		<section class="form-group clearfix">
			<%= f.label :設立月, class: "col-sm-4" %>
			<div class="col-sm-8">
				<%= f.text_field :establish_month, class: "form-control" %>
			</div>
		</section>
		<section class="form-group clearfix">
			<%= f.label :リンク, class: "col-sm-4" %>
			<div class="col-sm-8">
				<%= f.text_field :link, class: "form-control" %>
			</div>
		</section>
		<section class="form-group clearfix">
			<%= f.label :ミッションタイトル, class: "col-sm-4" %>
			<div class="col-sm-8">
				<%= f.text_field :mission_title, class: "form-control" %>		
			</div>
		</section>
		<section class="form-group clearfix">
			<%= f.label :ミッション本文, class: "col-sm-4" %>
			<div class="col-sm-8">
				<%= f.text_area :mission_body, class: "form-control" %>		
			</div>
		</section>
		<section class="form-group clearfix">
			<%= f.label :価値観, class: "col-sm-4" %>
			<div class="col-sm-8">
				<%= f.text_area :value, class: "form-control" %>		
			</div>
		</section>
		<section class="form-group clearfix">
			<%= f.label :なにをやっているのか, class: "col-sm-4" %>
			<div class="col-sm-8">
				<%= f.text_area :what, class: "form-control" %>	
			</div>
		</section>
		<section class="form-group clearfix">
			<%= f.label :なぜやるのか, class: "col-sm-4" %>
			<div class="col-sm-8">
				<%= f.text_area :why, class: "form-control" %>	
			</div>
		</section>
		<section class="form-group clearfix">
			<%= f.label :どうやっているのか, class: "col-sm-4" %>
			<div class="col-sm-8">
				<%= f.text_area :how, class: "form-control" %>	
			</div>
		</section>
		<section class="form-group">
			<%= f.fields_for :addresses do |builder| %>
				<%= render 'address_fields', f: builder %>
			<% end %>
		</section>
		<section class="form-group text-center">
			<%= link_to_add_association '住所を追加', f, :addresses, class: "btn btn-info" %>
		</section>
		<section class="form-group text-center">
			<%= f.submit '更新', class: "btn btn-success" %>
		</section>
	<% end %>
</div>

app/views/admin/companies/employee_index.html.erb
<%= flash[:notice] %>
<%= render 'sidebar', company: @company %>
<div class="col-sm-9">
    <table id="employee-table">
        <thead>
            <tr>
                <th>メンバー</th>
                <th>アカウント権限</th>
                <th>解除</th>
                <th><%= link_to '+社員を追加', admin_invite_new_path(@company), class: "btn btn-info" %></th>
            </tr>
        </thead>
        
        <tbody>
            <% @members.each do |member| %>
                <tr>
                    <td>
                        <%= attachment_image_tag member, :image, format: 'jpg', fallback: "no_image.jpg", size: '40x40' %>
                        <%= link_to member.name, user_path(member) %>
                    </td>
                    <td>
                        <% if member.id == current_user.id %>
                            <span>ログインユーザー</span>
                        <% elsif member.authority_status == "admin" %>
                            <%= link_to '管理者権限剥奪', admin_remove_authority_path(@company, member), data: { confirm: "管理者権限を剥奪しますか？"}, method: :post, class: "btn btn-warning" %>
                        <% else %>
                            <%= link_to '管理者権限付与', admin_add_authority_path(@company, member), data: { confirm: "管理者権限を付与しますか？"}, method: :post, class: "btn btn-success" %>
                        <% end %>
                    </td>    
                    <td>
                        <% if member.id == current_user.id %>
                            <span>ログインユーザー</span>
                        <% else %>
                            <%= link_to '社員登録解除', admin_remove_employee_path(@company, member), data: { confirm: 'この社員を登録解除しますか？'}, method: :post, class: "btn btn-danger" %>
                        <% end %>
                    </td>
                    <td></td>
                </tr>
        　   <% end %>
        </tbody>
        
    </table>

</div>

app/views/admin/companies/home.html.erb
<%= render 'sidebar', company: @company %>
<div class="col-sm-7">
    <h2 class="text-center">会社・社員情報</h2>
    <div class="home-link">
        <%= link_to '会社情報の編集へ', edit_admin_company_path(@company), class: "home-company-btn" %>
    </div>
    <div class="home-link">
        <%= link_to '社員一覧へ', admin_employee_index_path(@company), class: "home-employee-btn" %>
    </div>
</div>

app/views/admin/companies/invite_new.html.erb
<%= render 'sidebar', company: @company %>
<div class="col-sm-7">
    <h2 class="text-center">社員を追加</h2>
    <p id="invite-explain">追加したい社員のメールアドレスを入力して「招待メールを送る」をクリックすると、社員登録の招待メールが届きます。</p>
    <%= form_with local: true, url: admin_invite_path, method: :get do |f| %>
        <section class="form-group">
            <%= f.label :メールアドレスから追加 %>
            <%= f.email_field :email, class: "form-control" %>
        </section>
        <section class="form-group home-link">
            <%= f.submit '招待メールを送る', class: "btn btn-info" %>
        </section> 
    <% end %>
</div>