config/routes.rb
Rails.application.routes.draw do
  
  root 'companies#top'

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords'
  }

  resources :users, only: [:show, :edit, :update, :destroy]

  post 'rooms/:room_id/messages' => 'messages#create', as: "messages"
  get 'search' => 'recruits#search'
  get 'entries' => 'entries#index'
  get 'bookmarks' => 'bookmarks#index'
  get 'follows' => 'follows#index'

  resources :companies, only: [:show, :new, :create] do
    get 'users/:id/become_employee' => 'users#become_employee', as: 'become_employee'
    resources :rooms, only: [:show]
    resources :follows, only: [:create, :destroy]
  end

  get 'companies/:id/feeds' => 'feeds#company_feed', as: 'company_feed'
  get 'companies/:id/recruits' => 'recruits#company_index', as: 'company_index'
  get 'companies/:id/about' => 'companies#about', as: 'about'
  get 'companies/:id/members' => 'companies#member', as: 'member'

  resources :recruits, only: [:index, :show] do
    resources :entries, only: [:create]
    resources :supports, only: [:create]
    post 'bookmarks' => 'bookmarks#create'
    delete 'bookmarks' => 'bookmarks#destroy'
  end  

  resources :feeds, only: [:index, :show] do
    post 'favorites' => 'favorites#create'
    delete 'favorites' => 'favorites#destroy'
  end

  namespace :admin do
    post 'companies/:company_id/users/:id/add_employee' => 'companies#add_employee', as: 'add_employee'
    post 'companies/:company_id/users/:id/add_authority' => 'companies#add_authority', as: 'add_authority'
    get 'companies/:id/home' => 'companies#home'
    get 'companies/:id/users' => 'companies#employee_index', as: 'employee_index'
    get 'companies/:id/invite' => 'companies#invite', as: 'invite'
    get 'companies/:id/invite_new' => 'companies#invite_new', as: 'invite_new'
     
    resources :companies, only: [:edit, :update, :destroy] do
      resources :feeds, except: [:show]
      resources :recruits, except: [:show]
      post 'feeds/:id/update_status' => 'feeds#update_status', as: 'feed_update_status'
      post 'recruits/:id/update_status' => 'recruits#update_status', as: 'recruit_update_status'
      get 'candidates/:id' => 'entries#candidate_show', as: "candidate_show"
      get 'candidates' => 'entries#candidate_list'
    end 

    post 'companies/:company_id/users/:id/remove_employee' => 'companies#remove_employee', as: 'remove_employee'
    post 'companies/:company_id/users/:id/remove_authority' => 'companies#remove_authority', as: 'remove_authority'

    get 'scouts/search' => 'scouts#search'
    post 'users/:user_id/scouts' => 'scouts#create', as: 'scouts'
  end  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/recruit.rb
class Recruit < ApplicationRecord
    belongs_to :company
    has_many :bookmarks, dependent: :destroy
    has_many :supports, dependent: :destroy
    has_many :entries, dependent: :destroy
    has_many :recruit_features
    has_many :features, through: :recruit_features

    attachment :image

    enum occupation: { engineer: 0, designer: 1, directer: 2, cooperate: 3, sales: 4, marketing: 5, writer: 6, medical: 7, other: 8 }
    enum employment_status: { new_graduate: 0, internship: 1, mid_career: 2, side_job: 3 }
    enum status: { draft: 0, published: 1 }

    def self.recruit_search(search)
        return Recruit.where(status: 'published') unless search
        Recruit.where(['title LIKE ? OR do LIKE ? OR job_description LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%"]).where(status: 'published')
    end
end

app/controllers/admin/recruits_controller.rb
class Admin::RecruitsController < ApplicationController
  before_action :admin_user?
  before_action :find_recruit, only: [:edit, :update, :destroy, :update_status]

  def index
    @recruits = @company.recruits
  end

  def new
    @recruit = Recruit.new
    @features= Feature.all
  end

  def edit
    @features = Feature.all
  end

  def update_status
    if @recruit.status == 'draft'
      @recruit.status = 'published'
      @recruit.save
      flash[:success] = "募集を公開しました。"
    else
      @recruit.status = 'draft'
      @recruit.save
      flash[:alert] = "募集を公開停止にしました。"
    end
    redirect_to admin_company_recruits_path(@recruit)
  end


  def create
    @recruit = Recruit.new(recruit_params)
    @recruit.company_id = @company.id
    if @recruit.save
      flash[:success] = "募集を作成しました。"
      redirect_to admin_company_recruits_path(@company)
    else
      flash.now[:alert] = "募集の作成に失敗しました。"
      render :new
    end
  end

  def update
    if @recruit.update(recruit_params)
      flash[:success] = "募集を更新しました。"
      redirect_to admin_company_recruits_path(@company)
    else
      flash.now[:alert] = "募集の更新に失敗しました。"
      render :edit
    end
  end
  
  def destroy
    @recruit.destroy
    flash[:alert] = "募集を削除しました。"
    redirect_to admin_company_recruits_path
  end
  
  private

  def admin_user?
    if current_user.authority_status == "admin"
      @admin = current_user
      @company = @admin.company
    elsif user_signed_in?
      redirect_to recruits_path
    else
      redirect_to root_path
    end
  end

  def find_recruit
    @recruit = Recruit.find(params[:id])
  end

  def recruit_params
    params.require(:recruit).permit(:title, :do, :occupation, :job_description, :employment_status, :field, :image, :status ,feature_ids: [])
  end
end

app/controllers/recruits_controller.rb
class RecruitsController < ApplicationController

  def index
    if params[:recruit]
      @recruit_hash = params[:recruit].permit(:occupation, :employment_status).to_h
      @feature_hash = params[:feature].permit(:feature_id).to_h

      if @recruit_hash[:occupation].present?
        recruit1 = Recruit.where(occupation: @recruit_hash[:occupation], status: 'published')
      else
        recruit1 = Recruit.where(status: 'published')
      end

      if @recruit_hash[:employment_status].present?
        recruit2 = Recruit.where(employment_status: @recruit_hash[:employment_status], status: 'published')
      else
        recruit2 = Recruit.where(status: 'published')
      end

      if params[:search_word].present?
        recruit3 = Recruit.recruit_search(params[:search_word])
      else
        recruit3 = Recruit.where(status: 'published')
      end

      recruit4 = recruit1 & recruit2 & recruit3

      if @feature_hash[:feature_id].present?
        @recruits = []
        recruit4.each do |r|
          recruit_features1 = r.recruit_features.where(feature_id: @feature_hash[:feature_id].to_i)
          recruit_features1.each do |rf|
            @recruits << rf.recruit
          end
        end
      else
        @recruits = recruit4
      end
      
    else
      @recruits = Recruit.where(status: 'published')
    end
  end

  def show
    @recruit = Recruit.find(params[:id])
    @company = @recruit.company
    @members = @company.users.where(authority_status: "admin").sample(4)
    @recruit_feature = @recruit.recruit_features.find_by(feature_id: 2)
    @headquarters = @company.addresses.find_by(head_status: "head")
  end

  def company_index
    @company = Company.find(params[:id])
    @recruits = @company.recruits.where(status: 'published')
    @headquarters = @company.addresses.find_by(head_status: "head")
  end

  def search
    #検索画面で(search.html.erb)サイドバーのリンクが押されたら
    if params[:id] == "2"
      @companies = Company.all
    elsif params[:id] == "3"
      @users = User.all
    elsif params[:id] == "1"
      @recruits = Recruit.where(status: 'published')
    #ヘッダーからの検索とその他
    else
        @recruits = Recruit.recruit_search(params[:search])
        @companies = Company.company_search(params[:search])
        @users = User.user_search(params[:search])
    end

  end
end

app/helpers/admin/recruits_helper.rb
module Admin::RecruitsHelper
end

app/helpers/recruits_helper.rb
module RecruitsHelper
end

app/views/admin/recruits/edit.html.erb
<%= render 'admin/companies/sidebar', company: @company %>
<div class="col-sm-7">
	<h2 class="text-center">募集の編集</h2>
	<%= form_with model: @recruit, local: true, url: admin_company_recruit_path do |f| %>
		<section class="form-group">
			<%= f.label :タイトル %>
			<%= f.text_field :title, class: "form-control" %>
		</section>
		<section class="form-group">
			<%= f.label :画像 %>
			<%= f.attachment_field :image, class: "btn btn-file" %>
		</section>
		<section class="form-group">
			<%= f.label :こんなことやります %>
			<%= f.text_area :do, class: "form-control" %>
		</section>
		<section class="form-group">
			<%= f.label :詳細職種 %>
			<%= f.text_field :job_description, class: "form-control" %>
		</section>
		<section class="form-group">
			<%= f.label :職種 %>
			<%= f.select :occupation, Recruit.occupations_i18n.keys.map {|k| [I18n.t("enums.recruit.occupation.#{k}"), k]}, {}, class: "form-control" %>
		</section>
		<section class="form-group">
			<%= f.label :雇用形態 %>
			<%= f.select :employment_status, Recruit.employment_statuses_i18n.keys.map {|k| [I18n.t("enums.recruit.employment_status.#{k}"), k]}, {}, clas: "form-control" %>
		</section>
		<section class="form-group">
			<%= f.label :分野 %>
			<%= f.text_field :field, class: "form-control" %>
		</section>
		<section class="form-group">
			<%= f.label :ステータス %><br>
			<%= f.select :status, Recruit.statuses_i18n.keys.map{|k|[I18n.t("enums.recruit.status.#{k}"), k]}, {}, class: "form-control" %>
		</section>
		<section class="form-group">
			<%= f.label :特徴 %>
			<%= f.collection_check_boxes :feature_ids, @features, :id, :feature do |fe| %>
				<%= fe.label { fe.check_box + fe.text } %>
			<% end %>
		</section>
		<section class="form-group text-center">
			<%= f.submit '更新', class: "btn btn-success" %>
		</section>
	<% end %>
</div>

app/views/admin/recruits/index.html.erb
<%= render 'admin/companies/sidebar', company: @company %>
<div class="col-sm-9"> 
	<h2>募集</h2>
	<table class="index-table">
        <thead>
            <tr>
                <th>タイトル</th>
                <th>ステータス</th>
                <th>候補者</th>
				<th>削除</th>
				<th><%= link_to '募集を作成', new_admin_company_recruit_path, class: "btn btn-info" %></th>
            </tr>
        </thead>
        
        <tbody>
            <% @recruits.each do |recruit| %>
                <tr>
                    <td>
						<%= attachment_image_tag recruit, :image, format: 'jpg', size: '50x50' %>
						<div class="table-cell-inner">
							<%= link_to edit_admin_company_recruit_path(recruit.company, recruit), class: "black-link" do %>
								<%= recruit.title %> - <%= recruit.status_i18n %>
							<% end %>
							<div>
								<%= link_to '募集を表示', recruit_path(recruit) %> | <%= link_to '募集を編集', edit_admin_company_recruit_path(recruit.company, recruit) %>
							</div>
						</div>	
                    </td>
                    <td>
						<% if recruit.status == 'draft' %>
				   			<div><%= recruit.status_i18n %></div>
						   	<%= link_to '募集開始', admin_company_recruit_update_status_path(recruit.company, recruit), method: :post ,data: { confirm: "募集を開始しますか？" } %>
						<% else %>
							<div><%= recruit.status_i18n %></div>
							<%= link_to '募集停止', admin_company_recruit_update_status_path(recruit.company, recruit), method: :post , data: { confirm: "募集を停止しますか？" } %>
						<% end %>
					</td>
					<td><%= recruit.bookmarks.count %>人</td>
					<td><%= link_to '×', admin_company_recruit_path(recruit.company, recruit), method: :delete, data: { confirm: "この募集を削除しますか？" }, class: "btn btn-default" %></td>
					<td></td>
                </tr>
        　   <% end %>
        </tbody>
        
    </table>

</div>

app/views/admin/recruits/new.html.erb
<%= render 'admin/companies/sidebar', company: @company %>
<div class="col-sm-7">
	<h2 class="text-center">募集の作成</h2>
	<%= form_with model: @recruit, local: true, url: admin_company_recruits_path do |f| %>
		<section class="form-group">
			<%= f.label :画像 %>
			<%= f.attachment_field :image, class: "btn btn-file" %>
		</section>
		<section class="form-group">
			<%= f.label :タイトル %>
			<%= f.text_field :title, class: "form-control" %>
		</section>
		<section class="form-group">
			<%= f.label :こんなことやります %>
			<%= f.text_area :do, class: "form-control" %>
		</section>
		<section class="form-group">
			<%= f.label :詳細職種 %>
			<%= f.text_field :job_description, class:"form-control" %>
		</section>
		<section class="form-group">
			<%= f.label :職種 %>
			<%= f.select :occupation, Recruit.occupations_i18n.keys.map{|k| [I18n.t("enums.recruit.occupation.#{k}"), k]}, {} ,class: "form-control" %>
		</section>
		<section class="form-group">
			<%= f.label :雇用形態 %>
			<%= f.select :employment_status, Recruit.employment_statuses_i18n.keys.map{|k| [I18n.t("enums.recruit.employment_status.#{k}"), k]}, {} , class: "form-control" %>
		</section>
		<section class="form-group">
			<%= f.label :分野 %>
			<%= f.text_field :field, class: "form-control" %>
		</section>
		<section class="form-group">
			<%= f.label :ステータス %><br>
			<%= f.select :status, Recruit.statuses_i18n.keys.map{|k|[I18n.t("enums.recruit.status.#{k}"), k]}, {}, class: "form-control" %>
		</section>
		<section class="form-group">
			<%= f.label :特徴 %><br>
			<%= f.collection_check_boxes :feature_ids, @features, :id, :feature do |fe| %>
				<%= fe.label { fe.check_box + fe.text } %>
			<% end %>
		</section>
		<section class="form-group text-center">
			<%= f.submit '投稿', class: "btn btn-success" %>
		</section>
	<% end %>
</div>