config/routes.rb
Rails.application.routes.draw do
  
  root 'companies#top'

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords'
  }

  resources :users, only: [:show, :edit, :update, :destroy]

  post 'rooms/:room_id/messages' => 'messages#create', as: "messages"
  get 'search' => 'recruits#search'
  get 'entries' => 'entries#index'
  get 'bookmarks' => 'bookmarks#index'
  get 'follows' => 'follows#index'

  resources :companies, only: [:show, :new, :create] do
    get 'users/:id/become_employee' => 'users#become_employee', as: 'become_employee'
    resources :rooms, only: [:show]
    resources :follows, only: [:create, :destroy]
  end

  get 'companies/:id/feeds' => 'feeds#company_feed', as: 'company_feed'
  get 'companies/:id/recruits' => 'recruits#company_index', as: 'company_index'
  get 'companies/:id/about' => 'companies#about', as: 'about'
  get 'companies/:id/members' => 'companies#member', as: 'member'

  resources :recruits, only: [:index, :show] do
    resources :entries, only: [:create]
    resources :supports, only: [:create]
    post 'bookmarks' => 'bookmarks#create'
    delete 'bookmarks' => 'bookmarks#destroy'
  end  

  resources :feeds, only: [:index, :show] do
    post 'favorites' => 'favorites#create'
    delete 'favorites' => 'favorites#destroy'
  end

  namespace :admin do
    post 'companies/:company_id/users/:id/add_employee' => 'companies#add_employee', as: 'add_employee'
    post 'companies/:company_id/users/:id/add_authority' => 'companies#add_authority', as: 'add_authority'
    get 'companies/:id/home' => 'companies#home'
    get 'companies/:id/users' => 'companies#employee_index', as: 'employee_index'
    get 'companies/:id/invite' => 'companies#invite', as: 'invite'
    get 'companies/:id/invite_new' => 'companies#invite_new', as: 'invite_new'
     
    resources :companies, only: [:edit, :update, :destroy] do
      resources :feeds, except: [:show]
      resources :recruits, except: [:show]
      post 'feeds/:id/update_status' => 'feeds#update_status', as: 'feed_update_status'
      post 'recruits/:id/update_status' => 'recruits#update_status', as: 'recruit_update_status'
      get 'candidates/:id' => 'entries#candidate_show', as: "candidate_show"
      get 'candidates' => 'entries#candidate_list'
    end 

    post 'companies/:company_id/users/:id/remove_employee' => 'companies#remove_employee', as: 'remove_employee'
    post 'companies/:company_id/users/:id/remove_authority' => 'companies#remove_authority', as: 'remove_authority'

    get 'scouts/search' => 'scouts#search'
    post 'users/:user_id/scouts' => 'scouts#create', as: 'scouts'
  end  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
    has_many :users
    has_many :addresses, dependent: :destroy
    has_many :feeds, dependent: :destroy
    has_many :follows, dependent: :destroy
    has_many :scouts, dependent: :destroy
    has_many :recruits, dependent: :destroy
    has_many :rooms, dependent: :destroy

    acts_as_paranoid

    accepts_nested_attributes_for :addresses, allow_destroy: true

    attachment :logo

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    VALID_PHONE_NUMBER_REGEX = /\A\d{10,11}\z/

   
    validates :company_name, :person_name, presence: true, on: :create
    validates :email, format: { with: VALID_EMAIL_REGEX }, presence: true, on: :create
    validates :phone_number, format: { with: VALID_PHONE_NUMBER_REGEX }, presence: true, on: :create
    
    def self.company_search(search)
        return Company.all unless search
        Company.where(['company_name LIKE ?', "%#{search}%"])
    end
end

app/controllers/admin/companies_controller.rb
class Admin::CompaniesController < ApplicationController
	before_action :admin_user?, except: [:add_employee]

	def home
	end

	def edit
	    @company.addresses.build
	end

	def update
		if @company.update!(company_params)
			flash[:success] = "会社情報を更新しました。"
			redirect_to admin_path(@admin)
		else
			flash.now[:alert] = "更新に失敗しました。"
			render :edit
		end
	end

	def destroy
		@company = Company.find(params[:id])
		@company.destroy
		flash[:alert] = "会社アカウントを削除しました。"
		redirect_to recruits_path
	end

	def employee_index
		@members = @company.users
	end

	def invite_new
	end

	def invite
		if params[:email]
			user = User.find_by(email: params[:email])
			if user.company_id == nil || user.company_id != @company.id
				CompanyMailer.send_mail(user, @company).deliver
				flash[:info] = "招待メールを送りました。"
				redirect_to admin_employee_index_path
			else
				flash.now[:alert] = "すでに社員登録されています。"
				render :invite_new
			end
		end
	end

	def add_employee
		company = Company.find(params[:company_id])
		user = User.find(params[:id])
		user.company_id = company.id
		user.authority_status = "general"
		user.save
		flash[:success] = "社員登録に成功しました。"
		redirect_to recruits_path
	end

	def remove_employee
		member = User.find(params[:id])
		member.company_id = nil
		member.save
		flash[:alert] = "社員登録を解除しました。"
		redirect_to admin_employee_index_path
	end

	def add_authority
		member = User.find(params[:id])
		member.authority_status = "admin"
		member.save
		flash[:success] = "管理者権限を付与しました。"
		redirect_to admin_employee_index_path(member.company)
	end

	def remove_authority
		member = User.find(params[:id])
		member.authority_status = "general"
		member.save
		flash[:alert] = "管理者権限を削除しました。"
		redirect_to admin_employee_index_path(@admin.company)
	end

	private

	def admin_user?
		if current_user.authority_status == "admin"
			@admin = current_user
			@company = @admin.company
		elsif user_signed_in?
			redirect_to recruits_path
		else
			redirect_to root_path
		end
	end

	def company_params
		params.require(:company).permit(:logo, :establish_year, :establish_month, :link, :mission_title, :mission_body, :value, :what, :why, :how, addresses_attributes: [:id, :head_status, :postal_code, :prefecture, :address, :latitude, :longitude, :_destroy])
	end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  def top
  end

  def about
    @company = Company.find(params[:id])
    @headquarters = @company.addresses.find_by(head_status: "head")
  end

  def member
    @company = Company.find(params[:id])
    @headquarters = @company.addresses.find_by(head_status: "head")
    @members = @company.users
  end

  def show
    @company = Company.find(params[:id])
    @headquarters = @company.addresses.find_by(head_status: "head")
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    if User.find_by(email: @company.email)
      admin = User.find_by(email: @company.email)
      if admin.company_id.present?
        flash.now[:alert] = "会社の登録に失敗しました。"
        render :new
      else
        admin.name = @company.person_name
        admin.phone_number = @company.phone_number
        admin.authority_status = "admin"
        if @company.save
          admin.company_id = @company.id
          if admin.save
            sign_in(admin)
            flash[:success] = "会社を登録しました。"
            redirect_to edit_admin_company_path(@company)
          else
            @company.really_destroy!
            flash.now[:alert] = "会社の登録に失敗しました。"
            render :new
          end
        else
          flash.now[:alert] = "会社の登録に失敗しました。"
          render :new
        end
      end
    else
      admin = User.new
      admin.name = @company.person_name
      admin.email = @company.email
      admin.phone_number = @company.phone_number
      admin.authority_status = "admin"
      generated_password = Devise.friendly_token.first(12)
      admin.password = generated_password
      if @company.save
        admin.company_id = @company.id
        if admin.save(validate: false)
          sign_in(admin)
          PasswordMailer.send_password(admin, generated_password).deliver
          flash[:success] = "会社を登録しました。"
          redirect_to edit_admin_company_path(@company)
        else
          @company.really_destroy!
          flash.now[:alert] = "会社の登録に失敗しました。"
          render :new
        end
      else
        flash.now[:alert] = "会社の登録に失敗しました。"
        render :new
      end
    end

    
  end

  private

  def company_params
    params.require(:company).permit(:company_name, :person_name, :email, :phone_number)
  end

end

app/helpers/admin/companies_helper.rb
module Admin::CompaniesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
    class ErrorFormBuilder < ActionView::Helpers::FormBuilder
        def pick_errors(attribute)
            return nil if @object.nil? || (messages = @object.errors.messages[attribute]).nil?

            lis = messages.collect do |message|
                %{<li>#{@object.errors.full_message(attribute, message)}</li>}
            end.join

            %{<ul class="errors">#{lis}</ul}.html_safe
        end

        def text_field(attribute, options={})
            return super if options[:no_errors]
            super + pick_errors(attribute)
        end
    end
end

app/views/companies/_follow_form.html.erb
<% if !user_signed_in? %>
	<li class="follow_on">
		<%= link_to company_follows_path(company), method: :post, remote: true do %>
			<span>フォロー</span>
		<% end %>
	</li>
<% elsif follow = current_user.follows.find_by(company_id: company.id) %>
	<li class="follow_off">
		<%= link_to company_follow_path(company, follow), method: :delete, remote: true do %>
			<span>フォロー中</span>
		<% end %>
	</li>
<% else %>
	<li class="follow_on">
		<%= link_to company_follows_path(company), method: :post, remote: true do %>
			<span>フォロー</span>
		<% end %>
	</li>
<% end %>

app/views/companies/_header.html.erb
<div class="company-header">
	<%= attachment_image_tag company, :logo, size: '100x100' %>
	<div class="company-header-info">
		<h2><%= company.company_name %></h2>
		<div class="follow_btn_<%= company.id %> follow-btn">
			<%= render 'companies/follow_form', company: company, follow: @follow %>
		</div>
		<a href="<%= @company.link %>" class="company-header-link"><%= company.link %></a>
		<% if headquarters %>
			<span class="company-head"><i class="fas fa-map-marker-alt"></i><%= headquarters.prefecture %></span>
		<% end %>
	</div>
		
	<nav>
		<li><%= link_to 'ホーム', company_path(company) %></li>
		<li><%= link_to '私たちについて', about_path(company) %></li>
		<li><%= link_to 'メンバー', member_path(company) %></li>
		<li><%= link_to 'ストーリー', company_feed_path(company) %></li>
		<li><%= link_to '募集', company_index_path(company) %></li>
	</nav>
</div>

app/views/companies/about.html.erb
<%= render 'header', company: @company, headquarters: @headquarters %>
<div class="about-container">
	<section>
		<h2>なにをやっているのか</h2>
		<p><%= @company.what %></p>
	</section>
	<section>
		<h2>なぜやるのか</h2>
		<p><%= @company.why %></p>
	</section>
	<section>
		<h2>どうやっているのか</h2>
		<p><%= @company.how %></p>
	</section>
</div>

app/views/companies/member.html.erb
<%= render 'header', company: @company, headquarters: @headquarters %>
<div class="member-container">
	<ul>
		<% @members.each do |member| %>
			<%= link_to user_path(member) do %>
				<li>
					<%= attachment_image_tag member, :image, fallback: "no_image.jpg", size: '130x130' %>
					<h4><%= member.name %></h4>
				</li>		
			<% end %>
		<% end %>
	</ul>
</div>

app/views/companies/new.html.erb
<div class="notification">
        </div>
<div class="form-container">
    <h2 class="text-center">会社登録フォーム</h2>
    <%= form_with model: @company, builder: CompaniesHelper::ErrorFormBuilder, local: true, url: companies_path do |f| %>
        <div class="form-group">
            <%= f.label :会社名 %>
            <%= f.text_field :company_name, class: "form-control" %>
        </div>
        
        <div class="form-group">
            <%= f.label :担当者名 %>
            <%= f.text_field :person_name, class: "form-control" %>
        </div>
        
        <div class="form-group">
            <%= f.label :担当者メールアドレス %>
            <%= f.text_field :email, class: "form-control" %>
        </div>
        
        <div class="form-group">
            <%= f.label :担当者電話番号 %>
            <%= f.text_field :phone_number, class: "form-control" %>
        </div>
        
        <div class="form-group text-center">
            <%= f.submit '登録', class: "btn btn-success" %>
        </div>
    <% end %>
</div>

app/views/companies/show.html.erb
<%= render 'header', company: @company, headquarters: @headquarters %>
<div class="show-container">
	<section>
		<h2><%= @company.mission_title %></h2>
		<p><%= @company.mission_body %></p>
	</section>
	<section>
		<h2>価値観</h2>
		<p><%= @company.value %></p>
	</section>
	<div class="recruit-member">
		<h3>メンバー</h3>
		<ul>
			<% @company.users.each do |member| %>
				<%= link_to user_path(member) do %>
					<li>
						<%= attachment_image_tag member, :image, fallback: "no_image.jpg", size: '130x130' %>
						<h4><%= member.name %></h4>
					</li>		
				<% end %>
			<% end %>
		</ul>
	</div>
	<div class="footer-company-info">
		<div>
			<%= attachment_image_tag @company, :logo, size: '50x50' %>
			<h3><%= @company.company_name %></h3>
		</div>
	<% if @headquarters %>
		<li><i class="fas fa-map-marker-alt"></i><%= @headquarters.prefecture %><%= @headquarters.address %></li>
	<% end %>
		<li><i class="fas fa-link"></i><a href="<%= @company.link %>"><%= @company.link %></a></li>
		<li><i class="fas fa-flag"></i><%= @company.created_at.strftime('%Y/%m') %>に設立</li>
		<li><i class="fas fa-user"></i><%= @company.person_name %>が創業</li>
		<li><i class="fas fa-users"></i><%= @company.users.count %>人のメンバー</li>
	</div>
	<div id="map"></div>
</div>

<script>
function initMap() {
	var test = { lat: <%= @headquarters.latitude %>, lng: <%=@headquarters.longitude%> }
	var map = new google.maps.Map(document.getElementById('map'), {
		zoom: 15,
		center: test
	});
	var transitLayer = new google.maps.TransitLayer()
	transitLayer.setMap(map)

	var contentString = "#{@headquaters.address}"
	var infowindow = new google.maps.InfoWindow({
		content: contentString
	})

	var marker = new google.maps.Marker({
		position: test,
		map: map,
		title: contentString
	})

	marker.addListener('click', function() {
		infowindow.open(map, marker)
	})
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GEOCODING_API_KEY'] %>&callback=initMap" async defer></script>

app/views/companies/top.html.erb
<div class="col-sm-12">
    <h1>『はたらく』を面白く</h1>
    <p id="sub-title">Rは、月間1人が利用するビジネスSNSです</p>
    <li id="top-sign-up"><%= link_to 'emailで登録', new_user_registration_path, class: "btn btn-default" %></li>
</div>