config/routes.rb
Rails.application.routes.draw do
  
  root 'companies#top'

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords'
  }

  resources :users, only: [:show, :edit, :update, :destroy]

  post 'rooms/:room_id/messages' => 'messages#create', as: "messages"
  get 'search' => 'recruits#search'
  get 'entries' => 'entries#index'
  get 'bookmarks' => 'bookmarks#index'
  get 'follows' => 'follows#index'

  resources :companies, only: [:show, :new, :create] do
    get 'users/:id/become_employee' => 'users#become_employee', as: 'become_employee'
    resources :rooms, only: [:show]
    resources :follows, only: [:create, :destroy]
  end

  get 'companies/:id/feeds' => 'feeds#company_feed', as: 'company_feed'
  get 'companies/:id/recruits' => 'recruits#company_index', as: 'company_index'
  get 'companies/:id/about' => 'companies#about', as: 'about'
  get 'companies/:id/members' => 'companies#member', as: 'member'

  resources :recruits, only: [:index, :show] do
    resources :entries, only: [:create]
    resources :supports, only: [:create]
    post 'bookmarks' => 'bookmarks#create'
    delete 'bookmarks' => 'bookmarks#destroy'
  end  

  resources :feeds, only: [:index, :show] do
    post 'favorites' => 'favorites#create'
    delete 'favorites' => 'favorites#destroy'
  end

  namespace :admin do
    post 'companies/:company_id/users/:id/add_employee' => 'companies#add_employee', as: 'add_employee'
    post 'companies/:company_id/users/:id/add_authority' => 'companies#add_authority', as: 'add_authority'
    get 'companies/:id/home' => 'companies#home'
    get 'companies/:id/users' => 'companies#employee_index', as: 'employee_index'
    get 'companies/:id/invite' => 'companies#invite', as: 'invite'
    get 'companies/:id/invite_new' => 'companies#invite_new', as: 'invite_new'
     
    resources :companies, only: [:edit, :update, :destroy] do
      resources :feeds, except: [:show]
      resources :recruits, except: [:show]
      post 'feeds/:id/update_status' => 'feeds#update_status', as: 'feed_update_status'
      post 'recruits/:id/update_status' => 'recruits#update_status', as: 'recruit_update_status'
      get 'candidates/:id' => 'entries#candidate_show', as: "candidate_show"
      get 'candidates' => 'entries#candidate_list'
    end 

    post 'companies/:company_id/users/:id/remove_employee' => 'companies#remove_employee', as: 'remove_employee'
    post 'companies/:company_id/users/:id/remove_authority' => 'companies#remove_authority', as: 'remove_authority'

    get 'scouts/search' => 'scouts#search'
    post 'users/:user_id/scouts' => 'scouts#create', as: 'scouts'
  end  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/recruit.rb
class Recruit < ApplicationRecord
    belongs_to :company
    has_many :bookmarks, dependent: :destroy
    has_many :supports, dependent: :destroy
    has_many :entries, dependent: :destroy
    has_many :recruit_features
    has_many :features, through: :recruit_features

    attachment :image

    enum occupation: { engineer: 0, designer: 1, directer: 2, cooperate: 3, sales: 4, marketing: 5, writer: 6, medical: 7, other: 8 }
    enum employment_status: { new_graduate: 0, internship: 1, mid_career: 2, side_job: 3 }
    enum status: { draft: 0, published: 1 }

    def self.recruit_search(search)
        return Recruit.where(status: 'published') unless search
        Recruit.where(['title LIKE ? OR do LIKE ? OR job_description LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%"]).where(status: 'published')
    end
end

app/controllers/admin/recruits_controller.rb
class Admin::RecruitsController < ApplicationController
  before_action :admin_user?
  before_action :find_recruit, only: [:edit, :update, :destroy, :update_status]

  def index
    @recruits = @company.recruits
  end

  def new
    @recruit = Recruit.new
    @features= Feature.all
  end

  def edit
    @features = Feature.all
  end

  def update_status
    if @recruit.status == 'draft'
      @recruit.status = 'published'
      @recruit.save
      flash[:success] = "募集を公開しました。"
    else
      @recruit.status = 'draft'
      @recruit.save
      flash[:alert] = "募集を公開停止にしました。"
    end
    redirect_to admin_company_recruits_path(@recruit)
  end


  def create
    @recruit = Recruit.new(recruit_params)
    @recruit.company_id = @company.id
    if @recruit.save
      flash[:success] = "募集を作成しました。"
      redirect_to admin_company_recruits_path(@company)
    else
      flash.now[:alert] = "募集の作成に失敗しました。"
      render :new
    end
  end

  def update
    if @recruit.update(recruit_params)
      flash[:success] = "募集を更新しました。"
      redirect_to admin_company_recruits_path(@company)
    else
      flash.now[:alert] = "募集の更新に失敗しました。"
      render :edit
    end
  end
  
  def destroy
    @recruit.destroy
    flash[:alert] = "募集を削除しました。"
    redirect_to admin_company_recruits_path
  end
  
  private

  def admin_user?
    if current_user.authority_status == "admin"
      @admin = current_user
      @company = @admin.company
    elsif user_signed_in?
      redirect_to recruits_path
    else
      redirect_to root_path
    end
  end

  def find_recruit
    @recruit = Recruit.find(params[:id])
  end

  def recruit_params
    params.require(:recruit).permit(:title, :do, :occupation, :job_description, :employment_status, :field, :image, :status ,feature_ids: [])
  end
end

app/controllers/recruits_controller.rb
class RecruitsController < ApplicationController

  def index
    if params[:recruit]
      @recruit_hash = params[:recruit].permit(:occupation, :employment_status).to_h
      @feature_hash = params[:feature].permit(:feature_id).to_h

      if @recruit_hash[:occupation].present?
        recruit1 = Recruit.where(occupation: @recruit_hash[:occupation], status: 'published')
      else
        recruit1 = Recruit.where(status: 'published')
      end

      if @recruit_hash[:employment_status].present?
        recruit2 = Recruit.where(employment_status: @recruit_hash[:employment_status], status: 'published')
      else
        recruit2 = Recruit.where(status: 'published')
      end

      if params[:search_word].present?
        recruit3 = Recruit.recruit_search(params[:search_word])
      else
        recruit3 = Recruit.where(status: 'published')
      end

      recruit4 = recruit1 & recruit2 & recruit3

      if @feature_hash[:feature_id].present?
        @recruits = []
        recruit4.each do |r|
          recruit_features1 = r.recruit_features.where(feature_id: @feature_hash[:feature_id].to_i)
          recruit_features1.each do |rf|
            @recruits << rf.recruit
          end
        end
      else
        @recruits = recruit4
      end
      
    else
      @recruits = Recruit.where(status: 'published')
    end
  end

  def show
    @recruit = Recruit.find(params[:id])
    @company = @recruit.company
    @members = @company.users.where(authority_status: "admin").sample(4)
    @recruit_feature = @recruit.recruit_features.find_by(feature_id: 2)
    @headquarters = @company.addresses.find_by(head_status: "head")
  end

  def company_index
    @company = Company.find(params[:id])
    @recruits = @company.recruits.where(status: 'published')
    @headquarters = @company.addresses.find_by(head_status: "head")
  end

  def search
    #検索画面で(search.html.erb)サイドバーのリンクが押されたら
    if params[:id] == "2"
      @companies = Company.all
    elsif params[:id] == "3"
      @users = User.all
    elsif params[:id] == "1"
      @recruits = Recruit.where(status: 'published')
    #ヘッダーからの検索とその他
    else
        @recruits = Recruit.recruit_search(params[:search])
        @companies = Company.company_search(params[:search])
        @users = User.user_search(params[:search])
    end

  end
end

app/helpers/admin/recruits_helper.rb
module Admin::RecruitsHelper
end

app/helpers/recruits_helper.rb
module RecruitsHelper
end

app/views/recruits/_bookmark_form.html.erb
<% if !user_signed_in? %>
	<li class="bookmark_on">
		<%= link_to recruit_bookmarks_path(recruit), method: :post, remote: true do %>
			<i class="far fa-bookmark"></i>
		<% end %>
	</li>
<% elsif current_user.bookmarks.find_by(recruit_id: recruit.id) %>
	<li class="bookmark_off">
		<%= link_to recruit_bookmarks_path(recruit), method: :delete, remote: true do %>
			<i class="fas fa-bookmark"></i>
		<% end %>
	</li>
<% else %>
	<li class="bookmark_on">
		<%= link_to recruit_bookmarks_path(recruit), method: :post, remote: true do %>
			<i class="far fa-bookmark"></i>
		<% end %>
	</li>
<% end %>

app/views/recruits/company_index.html.erb
<%= render 'companies/header', company: @company, headquarters: @headquarters %>
<div class="company-index-container">
	<% @recruits.each do |recruit| %>
		<div class="link-container">
			<%= link_to recruit_path(recruit) do %>
				<%= attachment_image_tag recruit, :image %>
				<div class="recruit-content">	
					<div class="recruit-tags">
						<span class="job-description"><%= recruit.job_description %></span>
						<span><%= recruit.entries.count %>エントリー</span>
					</div>
					<h2><%= recruit.title %></h2>
					<p><%= strip_tags(recruit.do.to_s).gsub(/[\n]/,"").strip.truncate(120) %></p>
				</div>
			<% end %>
		</div>
		<div class="company-info">
			<%= link_to company_path(@company) do %>
				<%= attachment_image_tag @company, :logo, size: '50x50' %>
				<p><%= @company.company_name %></p>
			<% end %>
			<div id="bookmark_btn_<%= recruit.id %>" class="bookmark-link">
				<%= render 'bookmark_form', recruit: recruit, bookmark: @bookmark %>
			</div>
		</div>
	<% end %>
</div>

app/views/recruits/index.html.erb
<div class="col-sm-3">
	<h3>検索条件</h3>
	<%= form_tag recruits_path, method: :get do %>
		<%= text_field_tag :search_word, '', :placeholder => "キーワードで検索", class: "form-control" %><br>
		<%= select :recruit, :occupation, Recruit.occupations_i18n.keys.map {|k| [I18n.t("enums.recruit.occupation.#{k}"), k]}, {include_blank: true}, class: "form-control" %><br>
		<%= select :recruit, :employment_status, Recruit.employment_statuses_i18n.keys.map {|k| [I18n.t("enums.recruit.employment_status.#{k}"), k]}, {include_blank: true}, class: "form-control" %>
		<h5>特徴</h5>
		<%= collection_select(:feature, :feature_id, Feature.all, :id, :feature, {include_blank: true}, {class: "form-control"}) %><br>
		<%= submit_tag "この条件で検索する", :body => nil, class: "btn btn-info" %>
	<% end %>

</div>

<div class="col-sm-9">
	<% @recruits.each do |recruit| %>
		<div class="link-container">
			<%= link_to recruit_path(recruit) do %>
				<%= attachment_image_tag recruit, :image %>
				<div class="recruit-content">	
					<div class="recruit-tags">
						<span class="job-description"><%= recruit.job_description %></span>
						<span><%= recruit.entries.count %>エントリー</span>
					</div>
					<h2><%= recruit.title %></h2>
					<p><%= strip_tags(recruit.do.to_s).gsub(/[\n]/,"").strip.truncate(120) %></p>
				</div>
			<% end %>
		</div>
		<div class="company-info">
			<%= link_to company_path(recruit.company) do %>
				<%= attachment_image_tag recruit.company, :logo, size: '50x50' %>
				<p><%= recruit.company.company_name %></p>
			<% end %>
			<div id="bookmark_btn_<%= recruit.id %>" class="bookmark-link">
				<%= render 'bookmark_form', recruit: recruit, bookmark: @bookmark %>
			</div>
		</div>
	<% end %>
</div>

app/views/recruits/search.html.erb
<div class="col-sm-4">
    <div class="search-container">
        <h3>検索</h3>
        <ul>
            <li>
                <%= link_to search_path do %>
                    <i class="fas fa-th"></i><span>すべて</span>
                <% end %>
            </li>
            <li>
                <%= link_to search_path(id: 2) do %>
                    <i class="far fa-building"></i><span>会社</span>
                <% end %>
            </li>
            <li>
                <%= link_to search_path(id: 3) do %>
                    <i class="fas fa-user-alt"></i><span>プロフィール</span>
                <% end %>
            </li>
            <li>
                <%= link_to search_path(id: 1) do %>
                    <i class="fas fa-briefcase"></i><span>募集</span>
                <% end %>
            </li>
        </ul>
    </div>  
    
</div>
<div class="col-sm-8">
    <% if params[:id] == "2" %>
        <div class="result-container">
            <h3>会社</h3>
            <% @companies.each do |company| %>
                <%= link_to company_path(company) do %>
                    <div class="result-body">
                        <%= attachment_image_tag company, :logo, size: "80x80" %>
                        <div class="result-content">
                            <h4><%= company.company_name %></h4>
                            <p><%= company.link %></p>
                            <p><%= company.mission_body %></p>
                        </div>
                    </div>                 
                <% end %>
            <% end %>
        </div>
        
    <% elsif params[:id] == "3" %>
        <div class="result-container">
            <h3>プロフィール</h3>
            <% @users.each do |user| %>
                <%= link_to user_path(user) do %> 
                    <div class="result-body">
                        <%= attachment_image_tag user, :image, fallback: "no_image.jpg", size: "80x80" %>        
                        <div class="result-content">
                            <h4><%= user.name %></h4>
                            <% unless user.company_id == nil %>
                                <p><%= user.company.company_name %></p>
                            <% end %>
                        </div> 
                    </div>                    
                <% end %>
            <% end %>
        </div>
    <% elsif params[:id] == "1" %>
        <div class="result-container">
            <h3>募集</h3>
            <% @recruits.each do |recruit| %>
                <%= link_to recruit_path(recruit) do %>
                    <div class="result-body">
                        <%= attachment_image_tag recruit, :image, size: "80x80" %>
                        <div class="result-content">
                            <span><%= recruit.occupation_i18n %></span>
                            <h4><%= recruit.title %></h4>
                        </div>
                    </div>
                <% end %>
            <% end %>
        </div>
    <% elsif params[:recruit] %>
        <div class="result-container">
            <% @recruits.each do |recruit| %>
                <div class="link-container">
                    <%= link_to recruit_path(recruit) do %>
                        <%= attachment_image_tag recruit, :image %>
                            <div class="recruit-content">
                                <div class="recruit-tags">
                                    <span><%= recruit.job_description %></span>
                                    <span><%= recruit.entries.count %>エントリー</span>
                                </div>
                                <h2><%= recruit.title %></h2>
                                <p><%= strip_tags(recruit.do.to_s).gsub(/[\n]/,"").strip.truncate(120) %></p>
                            </div>
                    <% end %>
                </div>
                <div class="company-info">
                    <%= link_to company_path(recruit.company) do %>
                        <%= attachment_image_tag recruit.company, :logo, size: '50x50' %>
                        <p><%= recruit.company.company_name %></p>
                    <% end %>
                    <div id="bookmark_btn" class="bookmark-link">
                        <%= render 'bookmark_form', recruit: recruit %>
                    </div>
                </div>
            <% end %>
        </div>
    <% else %>
        <div class="result-container">
            <div class="sort-bar">
                <% if params[:searchword].present? %>
                    <strong><%= params[:search] %></strong>
                    で検索、
                <% end %>
                <strong><%= @recruits.size + @companies.size + @users.size %></strong>
                件見つかりました
            </div>
            <h3>募集</h3>
            <% @recruits.sample(1).each do |recruit| %>
                <%= link_to recruit_path(recruit) do %>
                    <div class="result-body">
                        <%= attachment_image_tag recruit, :image, size: "80x80" %>
                        <div class="result-content">
                            <span><%= recruit.occupation_i18n %></span>
                            <h4><%= recruit.title %></h4>
                        </div>
                    </div>
                <% end %>
            <% end %>
            <% if @recruits.size > 1 %>
                <div class="more"><%= link_to 'もっとみる', search_path(id: 1) %></div>
            <% end %>
        </div>
        <div class="result-container">
            <h3>会社</h3>
            <% @companies.sample(5).each do |company| %>
                <%= link_to company_path(company) do %>
                    <div class="result-body">
                        <%= attachment_image_tag company, :logo, size: "80x80" %>
                        <div class="result-content">
                            <h4><%= company.company_name %></h4>
                            <p><%= company.link %></p>
                            <p><%= company.mission_body %></p>
                        </div>
                    </div>                 
                <% end %>
            <% end %>
            <% if @companies.size > 1 %>
                <div class="more"><%= link_to 'もっとみる', search_path(id: 2) %></div>
            <% end %>
        </div>
        <div class="result-container">
            <h3>プロフィール</h3>
            <% @users.sample(5).each do |user| %>
                <%= link_to user_path(user) do %> 
                    <div class="result-body">
                        <%= attachment_image_tag user, :image, fallback: "no_image.jpg", size: "80x80" %>        
                        <div class="result-content">
                            <h4><%= user.name %></h4>
                            <% unless user.company_id == nil %>
                                <p><%= user.company.company_name %></p>
                            <% end %>
                        </div> 
                    </div>                    
                <% end %>
            <% end %>
            <% if @users.size > 1 %>
                <div class="more"><%= link_to 'もっとみる', search_path(id: 3) %></div>
            <% end %>
        </div>
    <% end %>
</div>

app/views/recruits/show.html.erb
<div class="recruit-show-container">
	<div class="recruit-show-header">
		<span><%= @recruit.job_description %></span>
		<span><strong><%= @recruit.entries.count %></strong>エントリー</span>
	</div>
	
	<h2><%= @recruit.title %></h2>

	<h3 class="recruit-show-company">
		<%= link_to company_path(@company) do %>
			<%= attachment_image_tag @company, :logo, size: '40x40' %>
			<p><%= @company.company_name %></p>
		<% end %>
	</h3>
	<div class="recruit-show-img">
		<%= attachment_image_tag @recruit, :image, size: '900x350' %>
	</div>
	<div class="recruit-tags">
		<span><i class="fas fa-map-marker-alt"></i><%= @headquarters.prefecture %></span>
		<span>
			<% if @recruit.employment_status == "new_graduate" %>
				<i class="fas fa-user-graduate"></i>
			<% elsif @recruit.employment_status == "internship" %>
				<i class="fas fa-user-graduate"></i>
			<% elsif @recruit.employment_status == "mid_career" %>
				<i class="fas fa-briefcase"></i>
			<% else %>
				<i class="fas fa-briefcase"></i>
			<% end %>
			<%= @recruit.employment_status_i18n %>
		</span>
		<% unless @recruit_feature.nil? %>
			<span><i class="fas fa-globe"></i>海外進出している</span>
		<% end %>
		<% if !user_signed_in? %>
			<span class="entry-link">
				<%= link_to '話を聞きに行きたい', recruit_entries_path(@recruit), method: :post, data: { confirm: "この募集にエントリーしますか？" } %>
			</span>
		<% elsif current_user.authority_status == "admin" %>
			<span class="entry-done">応募できません</span>
		<% elsif current_user.entries.find_by(recruit_id: @recruit.id) %>
			<span class="entry-done">エントリー済み</span>
		<% else %>
			<span class="entry-link">
				<%= link_to '話を聞きに行きたい', recruit_entries_path(@recruit), method: :post, data: { confirm: "この募集にエントリーしますか？" } %>
			</span>
		<% end %>
	</div>
	<div class="sidebar-left col-sm-8">
		<div class="recruit-member">
			<h3><%= @company.company_name %>のメンバー</h3>
			<ul>	
				<% @members.each do |member| %>
					<%= link_to user_path(member) do %>
						<li>
							<%= attachment_image_tag member, :image, fallback: "no_image.jpg", size: '130x130' %>
							<h4><%= member.name %></h4>		
						</li>
					<% end %>
				<% end %>
			</ul>
		</div>
		<section>
			<h3>なにをやっているのか</h3>
			<p><%= @company.what %></p>
		</section>
		<section>
			<h3>なぜやるのか</h3>
			<p><%= @company.why %></p>
		</section>
		<section>
			<h3>どうやってやるのか</h3>
			<p><%= @company.how %></p>
		</section>
		<section>
			<h3>こんなことやります</h3>
			<p><%= @recruit.do %></p>
		</section>
	</div>
	
	<div class="sidebar-right col-sm-4">
		<p class="side-content">
			<%= @recruit.entries.count %>人がエントリー中
		</p>
		<div id="bookmark_btn_<%= @recruit.id %>" class="side-bookmark">
			<%= render 'bookmark_form', recruit: @recruit, bookmark: @bookmark %>
		</div>
		<p class="side-content">
			<%= @recruit.supports.count %>人が応援しています
		</p>
		<div class="recruit-support">
			<% if !user_signed_in? %>
				<%= link_to '応援する', recruit_supports_path(@recruit), method: :post, data: { confirm: " この募集をTwitterで応援しますか？" } %>
			<% elsif current_user.supports.find_by(recruit_id: @recruit.id) %>
				応援済み
			<% else %>
				<%= link_to '応援する', recruit_supports_path(@recruit), method: :post, data: { confirm: " この募集をTwitterで応援しますか？" } %>
			<% end %>
		</div>
	</div>
</div>